
/*Copyright  © 2017 BUWANEKA DE SILVA

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files
(the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge,
publish, distribute, sublicense, and / or sell copies of the Software, and to permit persons to whom the Software is furnished to
do so, subject to the following conditions :The above copyright notice and this permission notice shall be included in all copies
or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR
IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.*/
package rws;

import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bpdesilva
 */
public class Home extends javax.swing.JFrame {

    Book b = new Book();
    Borrow bb = new Borrow();
    Reserve r = new Reserve();
    int loginUserId = 0;
    ArrayList allBorrowsList = new ArrayList();

    javax.swing.JButton activeButton;

    public Home(int loginUserId) {
        initComponents();
        jPanelReturnBook.setVisible(false);
        jPanelReserveBook.setVisible(false);
        jPanelBorrowedBooks.setVisible(false);
        jPaneloverdue.setVisible(false);
        this.loginUserId = loginUserId;
        populateTable t = new populateTable();
        t.searchData(borrowsTable, "SELECT b.ReferenceId,b.BookName,b.Genre,a.AuthorName,br.BorrowedDate,m.FirstName,m.LastName FROM book b \n"
                + "JOIN Author a ON a.idAuthor=b.AId\n"
                + "join borrow br on br.BId=b.idBook\n"
                + "join  member m on m.idMember=br.MId");
        btnBorrow.setForeground(Color.YELLOW);
        btnBorrow.setBackground(new Color(0, 0, 204));
        setLogedInAs();
    }

    private void setLogedInAs(){
        User u = new User();
        u.setUId(loginUserId);
        txtLoginAs.setText("Loged in as:  " + u.getUser(true));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelParent = new javax.swing.JPanel();
        jPanelSideBar = new javax.swing.JPanel();
        btnViewBorrowed = new javax.swing.JButton();
        btnBorrow = new javax.swing.JButton();
        btnReturn = new javax.swing.JButton();
        btnReserve = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblLoging = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbl = new javax.swing.JLabel();
        btnOverdue = new javax.swing.JButton();
        jPaneloverdue = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        finesTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanelBorrowedBooks = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        borrowsTable = new javax.swing.JTable();
        cmbxViewSelect = new javax.swing.JComboBox<>();
        jPanelReserveBook = new javax.swing.JPanel();
        txtSpRemarks1 = new javax.swing.JTextField();
        lblref1 = new javax.swing.JLabel();
        txtSearch1 = new javax.swing.JTextField();
        lblbk1 = new javax.swing.JLabel();
        txtBookName1 = new javax.swing.JTextField();
        lblauth1 = new javax.swing.JLabel();
        lblgenre1 = new javax.swing.JLabel();
        txtAuthor1 = new javax.swing.JTextField();
        lblSpRemarks1 = new javax.swing.JLabel();
        txtGenre1 = new javax.swing.JTextField();
        btnSearch1 = new javax.swing.JButton();
        txtRefId2 = new javax.swing.JTextField();
        lblSearch1 = new javax.swing.JLabel();
        cmbxOpt1 = new javax.swing.JComboBox<>();
        btnReserveBooks = new javax.swing.JButton();
        jPanelReturnBook = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnUpdateBooks1 = new javax.swing.JButton();
        selectBook = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jPanelBorrowBooks = new javax.swing.JPanel();
        lblref = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        lblbk = new javax.swing.JLabel();
        txtBookName = new javax.swing.JTextField();
        lblauth = new javax.swing.JLabel();
        lblgenre = new javax.swing.JLabel();
        txtAuthor = new javax.swing.JTextField();
        txtGenre = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        txtRefId = new javax.swing.JTextField();
        lblSearch = new javax.swing.JLabel();
        cmbxOpt = new javax.swing.JComboBox<>();
        btnBorrowBooks = new javax.swing.JButton();
        txtLoginAs = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelParent.setBackground(new java.awt.Color(255, 255, 255));
        jPanelParent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelSideBar.setBackground(new java.awt.Color(0, 51, 255));
        jPanelSideBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnViewBorrowed.setBackground(new java.awt.Color(0, 51, 255));
        btnViewBorrowed.setForeground(new java.awt.Color(255, 255, 255));
        btnViewBorrowed.setText("View Borrowed Books");
        btnViewBorrowed.setBorderPainted(false);
        btnViewBorrowed.setContentAreaFilled(false);
        btnViewBorrowed.setOpaque(true);
        btnViewBorrowed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnViewBorrowedMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnViewBorrowedMouseExited(evt);
            }
        });
        btnViewBorrowed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewBorrowedActionPerformed(evt);
            }
        });
        jPanelSideBar.add(btnViewBorrowed, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 220, 40));

        btnBorrow.setBackground(new java.awt.Color(0, 51, 255));
        btnBorrow.setForeground(new java.awt.Color(255, 255, 255));
        btnBorrow.setText("Borrow Book");
        btnBorrow.setBorderPainted(false);
        btnBorrow.setContentAreaFilled(false);
        btnBorrow.setOpaque(true);
        btnBorrow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBorrowMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBorrowMouseExited(evt);
            }
        });
        btnBorrow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrowActionPerformed(evt);
            }
        });
        jPanelSideBar.add(btnBorrow, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 220, 40));

        btnReturn.setBackground(new java.awt.Color(0, 51, 255));
        btnReturn.setForeground(new java.awt.Color(255, 255, 255));
        btnReturn.setText("Return Book");
        btnReturn.setBorderPainted(false);
        btnReturn.setContentAreaFilled(false);
        btnReturn.setOpaque(true);
        btnReturn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReturnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReturnMouseExited(evt);
            }
        });
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });
        jPanelSideBar.add(btnReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 220, 40));

        btnReserve.setBackground(new java.awt.Color(0, 51, 255));
        btnReserve.setForeground(new java.awt.Color(255, 255, 255));
        btnReserve.setText("Reserve Book");
        btnReserve.setBorderPainted(false);
        btnReserve.setContentAreaFilled(false);
        btnReserve.setOpaque(true);
        btnReserve.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReserveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReserveMouseExited(evt);
            }
        });
        btnReserve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReserveActionPerformed(evt);
            }
        });
        jPanelSideBar.add(btnReserve, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 220, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Nolan/icons8-key.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanelSideBar.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 30, 30));

        lblLoging.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Nolan/icons8-switch-power-off.png"))); // NOI18N
        lblLoging.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogingMouseClicked(evt);
            }
        });
        jPanelSideBar.add(lblLoging, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 620, 30, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Nolan/icons8-minus.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanelSideBar.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, 30, 30));

        lbl.setBackground(new java.awt.Color(51, 51, 51));
        lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appbackground/lbale4.png"))); // NOI18N
        jPanelSideBar.add(lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 670));

        btnOverdue.setBackground(new java.awt.Color(0, 51, 255));
        btnOverdue.setForeground(new java.awt.Color(255, 255, 255));
        btnOverdue.setText("View Overdue");
        btnOverdue.setBorderPainted(false);
        btnOverdue.setContentAreaFilled(false);
        btnOverdue.setOpaque(true);
        btnOverdue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnOverdueMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnOverdueMouseExited(evt);
            }
        });
        btnOverdue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOverdueActionPerformed(evt);
            }
        });
        jPanelSideBar.add(btnOverdue, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 220, 40));

        jPanelParent.add(jPanelSideBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 670));

        jPaneloverdue.setBackground(new java.awt.Color(255, 255, 255));
        jPaneloverdue.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        finesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(finesTable);

        jPaneloverdue.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 620, 350));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("View Overdue");
        jPaneloverdue.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        jPanelParent.add(jPaneloverdue, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 880, 560));

        jPanelBorrowedBooks.setBackground(new java.awt.Color(255, 255, 255));
        jPanelBorrowedBooks.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("View Borrowed Books");
        jPanelBorrowedBooks.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, -1));

        borrowsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(borrowsTable);

        jPanelBorrowedBooks.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 620, 330));

        cmbxViewSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Borrowal History", "Future Borrows" }));
        cmbxViewSelect.setSelectedIndex(1);
        cmbxViewSelect.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbxViewSelectItemStateChanged(evt);
            }
        });
        jPanelBorrowedBooks.add(cmbxViewSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 310, 30));

        jPanelParent.add(jPanelBorrowedBooks, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 880, 560));

        jPanelReserveBook.setBackground(new java.awt.Color(255, 255, 255));
        jPanelReserveBook.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtSpRemarks1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSpRemarks1ActionPerformed(evt);
            }
        });
        jPanelReserveBook.add(txtSpRemarks1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 350, 30));

        lblref1.setText("Refernce ID");
        jPanelReserveBook.add(lblref1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));

        txtSearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearch1ActionPerformed(evt);
            }
        });
        jPanelReserveBook.add(txtSearch1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 350, 30));

        lblbk1.setText("Book Name");
        jPanelReserveBook.add(lblbk1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));

        txtBookName1.setEditable(false);
        jPanelReserveBook.add(txtBookName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 350, 30));

        lblauth1.setText("Author");
        jPanelReserveBook.add(lblauth1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, -1));

        lblgenre1.setText("Genre");
        jPanelReserveBook.add(lblgenre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, -1, 20));

        txtAuthor1.setEditable(false);
        txtAuthor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAuthor1ActionPerformed(evt);
            }
        });
        jPanelReserveBook.add(txtAuthor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 350, 30));

        lblSpRemarks1.setText("Special Remarks");
        lblSpRemarks1.setToolTipText("");
        jPanelReserveBook.add(lblSpRemarks1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, -1, 20));

        txtGenre1.setEditable(false);
        txtGenre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGenre1ActionPerformed(evt);
            }
        });
        jPanelReserveBook.add(txtGenre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 350, 30));

        btnSearch1.setBackground(new java.awt.Color(0, 153, 153));
        btnSearch1.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch1.setText("Search Book");
        btnSearch1.setBorderPainted(false);
        btnSearch1.setContentAreaFilled(false);
        btnSearch1.setOpaque(true);
        btnSearch1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSearch1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSearch1MouseExited(evt);
            }
        });
        btnSearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearch1ActionPerformed(evt);
            }
        });
        jPanelReserveBook.add(btnSearch1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 70, 110, 30));

        txtRefId2.setEditable(false);
        txtRefId2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRefId2ActionPerformed(evt);
            }
        });
        jPanelReserveBook.add(txtRefId2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 350, 30));

        lblSearch1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblSearch1.setText("Search");
        jPanelReserveBook.add(lblSearch1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        cmbxOpt1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "By Id", "By Name" }));
        jPanelReserveBook.add(cmbxOpt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 110, 30));

        btnReserveBooks.setBackground(new java.awt.Color(0, 153, 153));
        btnReserveBooks.setForeground(new java.awt.Color(255, 255, 255));
        btnReserveBooks.setText("Reserve Book");
        btnReserveBooks.setBorderPainted(false);
        btnReserveBooks.setContentAreaFilled(false);
        btnReserveBooks.setOpaque(true);
        btnReserveBooks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReserveBooksMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReserveBooksMouseExited(evt);
            }
        });
        btnReserveBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReserveBooksActionPerformed(evt);
            }
        });
        jPanelReserveBook.add(btnReserveBooks, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 390, 120, 40));

        jPanelParent.add(jPanelReserveBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 880, 560));

        jPanelReturnBook.setBackground(new java.awt.Color(255, 255, 255));
        jPanelReturnBook.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Return Books");
        jPanelReturnBook.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        btnUpdateBooks1.setBackground(new java.awt.Color(0, 153, 153));
        btnUpdateBooks1.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateBooks1.setText("Return Book");
        btnUpdateBooks1.setBorderPainted(false);
        btnUpdateBooks1.setContentAreaFilled(false);
        btnUpdateBooks1.setOpaque(true);
        btnUpdateBooks1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUpdateBooks1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUpdateBooks1MouseExited(evt);
            }
        });
        btnUpdateBooks1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateBooks1ActionPerformed(evt);
            }
        });
        jPanelReturnBook.add(btnUpdateBooks1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 120, 40));

        jPanelReturnBook.add(selectBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 420, 30));

        jLabel7.setText("Select the Book to Return");
        jPanelReturnBook.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 150, -1));

        jPanelParent.add(jPanelReturnBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 880, 560));

        jPanelBorrowBooks.setBackground(new java.awt.Color(255, 255, 255));
        jPanelBorrowBooks.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblref.setText("Refernce ID");
        jPanelBorrowBooks.add(lblref, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        jPanelBorrowBooks.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 350, 30));

        lblbk.setText("Book Name");
        jPanelBorrowBooks.add(lblbk, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));

        txtBookName.setEditable(false);
        jPanelBorrowBooks.add(txtBookName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 350, 30));

        lblauth.setText("Author");
        jPanelBorrowBooks.add(lblauth, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, -1));

        lblgenre.setText("Genre");
        jPanelBorrowBooks.add(lblgenre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, -1, 20));

        txtAuthor.setEditable(false);
        txtAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAuthorActionPerformed(evt);
            }
        });
        jPanelBorrowBooks.add(txtAuthor, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 350, 30));

        txtGenre.setEditable(false);
        txtGenre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGenreActionPerformed(evt);
            }
        });
        jPanelBorrowBooks.add(txtGenre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 350, 30));

        btnSearch.setBackground(new java.awt.Color(0, 153, 153));
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("Search Book");
        btnSearch.setBorderPainted(false);
        btnSearch.setContentAreaFilled(false);
        btnSearch.setOpaque(true);
        btnSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSearchMouseExited(evt);
            }
        });
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jPanelBorrowBooks.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 70, 110, 30));

        txtRefId.setEditable(false);
        txtRefId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRefIdActionPerformed(evt);
            }
        });
        jPanelBorrowBooks.add(txtRefId, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 350, 30));

        lblSearch.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblSearch.setText("Search");
        jPanelBorrowBooks.add(lblSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        cmbxOpt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "By Id", "By Name" }));
        jPanelBorrowBooks.add(cmbxOpt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 110, 30));

        btnBorrowBooks.setBackground(new java.awt.Color(0, 153, 153));
        btnBorrowBooks.setForeground(new java.awt.Color(255, 255, 255));
        btnBorrowBooks.setText("Borrow Books");
        btnBorrowBooks.setBorderPainted(false);
        btnBorrowBooks.setContentAreaFilled(false);
        btnBorrowBooks.setOpaque(true);
        btnBorrowBooks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBorrowBooksMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBorrowBooksMouseExited(evt);
            }
        });
        btnBorrowBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrowBooksActionPerformed(evt);
            }
        });
        jPanelBorrowBooks.add(btnBorrowBooks, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 350, 120, 40));

        jPanelParent.add(jPanelBorrowBooks, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 880, 560));

        txtLoginAs.setEditable(false);
        txtLoginAs.setText("Loged in as:");
        txtLoginAs.setEnabled(false);
        jPanelParent.add(txtLoginAs, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 10, 280, 30));

        getContentPane().add(jPanelParent, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1180, 670));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Nolan/icons8-minus.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, 30, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        activeButton = btnReturn;
        resetButtonBackgrounds();
        btnReturn.setForeground(Color.YELLOW);
        btnReturn.setBackground(new Color(0, 0, 204));

        jPanelReturnBook.setVisible(true);
        jPanelBorrowBooks.setVisible(false);
        jPanelReserveBook.setVisible(false);
        jPanelBorrowedBooks.setVisible(false);
        jPaneloverdue.setVisible(false);
        initReturningBooks();
    }//GEN-LAST:event_btnReturnActionPerformed

    private void initReturningBooks() {
        selectBook.removeAllItems();
        bb.setMId(loginUserId);
        allBorrowsList = bb.getAllBorrows();
        for (int i = 0; i < allBorrowsList.size(); i++) {
            String[] borrow = (String[]) allBorrowsList.get(i);
            String book = "BookID " + borrow[1] + " due to " + borrow[3];
            selectBook.addItem(book);
        }
    }
    private void btnBorrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrowActionPerformed
        activeButton = btnBorrow;
        resetButtonBackgrounds();
        btnBorrow.setForeground(Color.YELLOW);
        btnBorrow.setBackground(new Color(0, 0, 204));

        jPanelBorrowBooks.setVisible(true);
        jPanelReturnBook.setVisible(false);
        jPanelReserveBook.setVisible(false);
        jPanelBorrowedBooks.setVisible(false);
        jPaneloverdue.setVisible(false);
    }//GEN-LAST:event_btnBorrowActionPerformed

    private void btnReserveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReserveActionPerformed
        activeButton = btnReserve;
        resetButtonBackgrounds();
        btnReserve.setForeground(Color.YELLOW);
        btnReserve.setBackground(new Color(0, 0, 204));

        jPanelReserveBook.setVisible(true);
        jPanelReturnBook.setVisible(false);
        jPanelBorrowBooks.setVisible(false);
        jPanelBorrowedBooks.setVisible(false);
        jPaneloverdue.setVisible(false);
        txtSpRemarks1.setEnabled(false);
        btnReserveBooks.setEnabled(false);
    }//GEN-LAST:event_btnReserveActionPerformed

    private void btnViewBorrowedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewBorrowedActionPerformed
        activeButton = btnViewBorrowed;
        resetButtonBackgrounds();
        btnViewBorrowed.setForeground(Color.YELLOW);
        btnViewBorrowed.setBackground(new Color(0, 0, 204));

        jPanelBorrowedBooks.setVisible(true);
        jPanelReserveBook.setVisible(false);
        jPanelReturnBook.setVisible(false);
        jPanelBorrowBooks.setVisible(false);
        jPaneloverdue.setVisible(false);
        setBorrowedTable();
    }//GEN-LAST:event_btnViewBorrowedActionPerformed

    private void setBorrowedTable() {
        bb.setMId(loginUserId);
        ArrayList allBorrowsFuture = bb.getAllBorrows();
        ArrayList allBorrowsHistory = bb.getAllBorrowsHistory();

        ArrayList allBorrowsList;
        String fourthColumn;
        if (cmbxViewSelect.getSelectedIndex() == 1) {
            allBorrowsList = allBorrowsFuture;
            fourthColumn = "Due Date";
        } else {
            allBorrowsList = allBorrowsHistory;
            fourthColumn = "Returned On";
        }
        borrowsTable.removeAll();
        DefaultTableModel borrowsTableModel = (DefaultTableModel) borrowsTable.getModel();
        int rowCount = borrowsTableModel.getRowCount();
        for (int i = 0; i < rowCount; i++) {
            borrowsTableModel.removeRow(0);
        }
        String[] header = {"Book Ref", "Member Id", "Borrowed", fourthColumn};
        DefaultTableModel dtm = new DefaultTableModel() {
            public boolean isCelEditable(int row, int coll) {
                return coll != 1;
            }
        };
        dtm.setColumnIdentifiers(header);
        borrowsTable.setModel(dtm);
        for (int i = 0; i < allBorrowsList.size(); i++) {
            String[] borrowData = (String[]) allBorrowsList.get(i);
            String[] tableRow = new String[4];
            tableRow[0] = borrowData[1];
            tableRow[1] = borrowData[2];
            tableRow[2] = borrowData[4];
            tableRow[3] = borrowData[3];
            dtm.addRow(tableRow);
            borrowsTable.setModel(dtm);
        }
    }

    private void resetButtonBackgrounds() {
        javax.swing.JButton[] leftPanel = {
            btnViewBorrowed,
            btnReturn,
            btnOverdue,
            btnBorrow,
            btnReserve
        };

        for (javax.swing.JButton button : leftPanel) {
            if (activeButton != button) {
                button.setForeground(new Color(255, 255, 255));
                button.setBackground(new Color(0, 51, 255));
            }
        }
    }

    private void btnBorrowMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBorrowMouseEntered
        btnBorrow.setForeground(Color.YELLOW);
        btnBorrow.setBackground(new Color(0, 0, 204));
    }//GEN-LAST:event_btnBorrowMouseEntered

    private void btnBorrowMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBorrowMouseExited
        if (activeButton != btnBorrow) {
            btnBorrow.setForeground(new Color(255, 255, 255));
            btnBorrow.setBackground(new Color(0, 51, 255));
        }
    }//GEN-LAST:event_btnBorrowMouseExited

    private void btnReturnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReturnMouseEntered
        btnReturn.setForeground(Color.YELLOW);
        btnReturn.setBackground(new Color(0, 0, 204));
    }//GEN-LAST:event_btnReturnMouseEntered

    private void btnReserveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReserveMouseEntered
        btnReserve.setForeground(Color.YELLOW);
        btnReserve.setBackground(new Color(0, 0, 204));
    }//GEN-LAST:event_btnReserveMouseEntered

    private void btnViewBorrowedMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewBorrowedMouseEntered
        btnViewBorrowed.setForeground(Color.YELLOW);
        btnViewBorrowed.setBackground(new Color(0, 0, 204));
    }//GEN-LAST:event_btnViewBorrowedMouseEntered

    private void btnReturnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReturnMouseExited
        if (activeButton != btnReturn) {
            btnReturn.setForeground(new Color(255, 255, 255));
            btnReturn.setBackground(new Color(0, 51, 255));
        }
    }//GEN-LAST:event_btnReturnMouseExited

    private void btnReserveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReserveMouseExited
        if (activeButton != btnReserve) {
            btnReserve.setForeground(new Color(255, 255, 255));
            btnReserve.setBackground(new Color(0, 51, 255));
        }
    }//GEN-LAST:event_btnReserveMouseExited

    private void btnViewBorrowedMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewBorrowedMouseExited
        if (activeButton != btnViewBorrowed) {
            btnViewBorrowed.setForeground(new Color(255, 255, 255));
            btnViewBorrowed.setBackground(new Color(0, 51, 255));
        }
    }//GEN-LAST:event_btnViewBorrowedMouseExited

    private void btnOverdueMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOverdueMouseEntered
        btnOverdue.setForeground(Color.YELLOW);
        btnOverdue.setBackground(new Color(0, 0, 204));
    }//GEN-LAST:event_btnOverdueMouseEntered

    private void btnOverdueMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOverdueMouseExited
        if (activeButton != btnOverdue) {
            btnOverdue.setForeground(new Color(255, 255, 255));
            btnOverdue.setBackground(new Color(0, 51, 255));
        }
    }//GEN-LAST:event_btnOverdueMouseExited

    private void btnOverdueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOverdueActionPerformed
        activeButton = btnOverdue;
        resetButtonBackgrounds();
        btnOverdue.setForeground(Color.YELLOW);
        btnOverdue.setBackground(new Color(0, 0, 204));

        jPaneloverdue.setVisible(true);
        jPanelReserveBook.setVisible(false);
        jPanelReturnBook.setVisible(false);
        jPanelBorrowBooks.setVisible(false);
        jPanelBorrowedBooks.setVisible(false);
        setFinesTable();
    }//GEN-LAST:event_btnOverdueActionPerformed

    private void setFinesTable() {
        bb.setMId(loginUserId);
        if (!allBorrowsList.isEmpty()) {
            allBorrowsList.clear();
        }
        allBorrowsList = bb.getAllBorrows();

        finesTable.removeAll();
        DefaultTableModel finesTableModel = (DefaultTableModel) finesTable.getModel();
        int rowCount = finesTableModel.getRowCount();
        for (int i = 0; i < rowCount; i++) {
            finesTableModel.removeRow(0);
        }
        String[] header = {"Book Ref", "Borrowed", "Due Date", "Fines"};
        DefaultTableModel dtm = new DefaultTableModel() {
            public boolean isCelEditable(int row, int coll) {
                return coll != 1;
            }
        };
        dtm.setColumnIdentifiers(header);
        finesTable.setModel(dtm);
        for (int i = 0; i < allBorrowsList.size(); i++) {
            String[] borrowData = (String[]) allBorrowsList.get(i);
            if (Integer.parseInt(borrowData[2]) == loginUserId) {
                String[] tableRow = new String[4];
                tableRow[0] = borrowData[1];
                tableRow[1] = borrowData[6];
                tableRow[2] = borrowData[3];
                tableRow[3] = borrowData[5];
                dtm.addRow(tableRow);
                finesTable.setModel(dtm);
            }
        }
    }

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        btnSearchActionPerformed(evt);
    }//GEN-LAST:event_txtSearchActionPerformed

    private void txtAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAuthorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAuthorActionPerformed

    private void txtGenreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGenreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGenreActionPerformed

    private void btnSearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchMouseEntered

    private void btnSearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchMouseExited

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String opt = cmbxOpt.getSelectedItem().toString();
        String ref = txtSearch.getText();
        switch (opt) {
            case "By Id":
                b.SearchBookById(ref);
                String ref2 = "" + b.getRefId();
                if (ref.equalsIgnoreCase(ref2)) {
                    txtRefId.setText(ref);
                    txtBookName.setText(b.getBookName());
                    txtAuthor.setText(b.getAuthName());
                    txtGenre.setText(b.getGenre());
                } else {
                    JOptionPane.showMessageDialog(null, "Entered Book Id Was Not Found!");
                }
                break;
            case "By Name":
                b.SearchBookByName(txtSearch.getText());
                String bookName = b.getBookName();
                if (bookName.equalsIgnoreCase(ref)) {
                    txtRefId.setText("" + b.getRefId());
                    txtBookName.setText(ref);
                    txtAuthor.setText(b.getAuthName());
                    txtGenre.setText(b.getGenre());
                } else {
                    JOptionPane.showMessageDialog(null, "Entered Book Name Was Not Found!");
                }
                break;
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void txtRefIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRefIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRefIdActionPerformed

    private void btnBorrowBooksMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBorrowBooksMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBorrowBooksMouseEntered

    private void btnBorrowBooksMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBorrowBooksMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBorrowBooksMouseExited

    private void btnBorrowBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrowBooksActionPerformed
        bb.setBId(Integer.parseInt(txtRefId.getText()));
        bb.setMId(loginUserId);
        int borrowalStatus = bb.addBorrow();
        switch (borrowalStatus) {
            case 0:
                JOptionPane.showMessageDialog(null, "Borrowal transaction was Failed due to Login Error. Plese Re-Login and try again!");
                break;
            case 1:
                JOptionPane.showMessageDialog(null, "User has exceeded maximum Borrowal Limit!");
                break;
            case 2:
                JOptionPane.showMessageDialog(null, "The book you going to Borrow was already borrowed!");
                break;
            case 3:
                JOptionPane.showMessageDialog(null, "The book you going to Borrow was Reserved!");
                break;
            case 4:
                JOptionPane.showMessageDialog(null, "Borrowal transaction was succesful!");
                txtRefId.setText("");
                txtAuthor.setText("");
                txtSearch.setText("");
                txtBookName.setText("");
                txtGenre.setText("");
                break;
        }
    }//GEN-LAST:event_btnBorrowBooksActionPerformed

    private void txtSpRemarks1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSpRemarks1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSpRemarks1ActionPerformed

    private void txtSearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearch1ActionPerformed
        btnSearch1ActionPerformed(evt);
    }//GEN-LAST:event_txtSearch1ActionPerformed

    private void txtAuthor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAuthor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAuthor1ActionPerformed

    private void txtGenre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGenre1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGenre1ActionPerformed

    private void btnSearch1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearch1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearch1MouseEntered

    private void btnSearch1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearch1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearch1MouseExited

    private void btnSearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearch1ActionPerformed
        String opt = cmbxOpt1.getSelectedItem().toString();
        String ref = txtSearch1.getText();
        switch (opt) {
            case "By Id":
                b.SearchBookById(ref);
                String ref2 = "" + b.getRefId();
                if (ref.equalsIgnoreCase(ref2)) {
                    txtRefId2.setText(ref);
                    txtBookName1.setText(b.getBookName());
                    txtAuthor1.setText(b.getAuthName());
                    txtGenre1.setText(b.getGenre());
                    txtSpRemarks1.setEnabled(true);
                    btnReserveBooks.setEnabled(true);
                } else {
                    JOptionPane.showMessageDialog(null, "Entered Book Id Was Not Found!");
                }
                break;
            case "By Name":
                b.SearchBookByName(txtSearch.getText());
                String bookName = b.getBookName();
                if (bookName.equalsIgnoreCase(ref)) {
                    txtRefId2.setText("" + b.getRefId());
                    txtBookName1.setText(ref);
                    txtAuthor1.setText(b.getAuthName());
                    txtGenre1.setText(b.getGenre());
                    txtSpRemarks1.setEnabled(true);
                    btnReserveBooks.setEnabled(true);
                } else {
                    JOptionPane.showMessageDialog(null, "Entered Book Name Was Not Found!");
                }
                break;
        }
    }//GEN-LAST:event_btnSearch1ActionPerformed

    private void txtRefId2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRefId2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRefId2ActionPerformed

    private void btnReserveBooksMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReserveBooksMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReserveBooksMouseEntered

    private void btnReserveBooksMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReserveBooksMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReserveBooksMouseExited

    private void btnReserveBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReserveBooksActionPerformed
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        String reservedDate = dateFormat.format(new Date());
        r.setBId(Integer.parseInt(txtRefId2.getText()));
        r.setSpecialRemark(txtSpRemarks1.getText());
        r.setMId(loginUserId);
        r.setReservedDate(reservedDate);
        int reservationStatus = r.addReserve();
        switch (reservationStatus) {
            case 0:
                JOptionPane.showMessageDialog(null, "Reservation transaction was Failed due to Login Error. Plese Re-Login and try again!");
                break;
            case 1:
                JOptionPane.showMessageDialog(null, "User has exceeded maximum Reservation Limit!");
                break;
            case 2:
                JOptionPane.showMessageDialog(null, "The book you going to Reserve was Already Reserved!");
                break;
            case 3:
                JOptionPane.showMessageDialog(null, "Reservation transaction was succesful!");
                JOptionPane.showMessageDialog(null, "Please note that reservations are valid only for one week!");
                txtRefId2.setText("");
                txtAuthor1.setText("");
                txtSearch1.setText("");
                txtBookName1.setText("");
                txtGenre1.setText("");
                txtSpRemarks1.setText("");
                break;
        }
    }//GEN-LAST:event_btnReserveBooksActionPerformed

    private void btnUpdateBooks1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateBooks1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateBooks1MouseEntered

    private void btnUpdateBooks1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateBooks1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateBooks1MouseExited

    private void btnUpdateBooks1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateBooks1ActionPerformed
        int selectedBorrow = selectBook.getSelectedIndex();
        String[] borrowalData = (String[]) allBorrowsList.get(selectedBorrow);
        int selectedIdBorrow = Integer.parseInt(borrowalData[0]);
        int selectedBRef = Integer.parseInt(borrowalData[1]);
        bb.deleteBorrow(selectedIdBorrow, selectedBRef);
        JOptionPane.showMessageDialog(null, "Borrowed book was succesfuly returned!");
        selectBook.removeItemAt(selectedBorrow);
    }//GEN-LAST:event_btnUpdateBooks1ActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        this.setState(ICONIFIED);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        this.setState(ICONIFIED);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        int p = JOptionPane.showConfirmDialog(null, "DO YOU WANT LOGOUT, ?", "", JOptionPane.YES_NO_OPTION);

        if (p == 0) {
            login lg = new login();
            this.setVisible(false);
            lg.setVisible(true);
        } else {
            System.gc();
        }
    }//GEN-LAST:event_jLabel2MouseClicked

    private void lblLogingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogingMouseClicked
        int p = JOptionPane.showConfirmDialog(null, "DO YOU WANT CLOSE, ?", "", JOptionPane.YES_NO_OPTION);

        if (p == 0) {
            DBConnection.closeConnection();
            System.exit(0);
        } else {
            System.gc();
        }
    }//GEN-LAST:event_lblLogingMouseClicked

    private void cmbxViewSelectItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbxViewSelectItemStateChanged
        setBorrowedTable();
    }//GEN-LAST:event_cmbxViewSelectItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable borrowsTable;
    private javax.swing.JButton btnBorrow;
    private javax.swing.JButton btnBorrowBooks;
    private javax.swing.JButton btnOverdue;
    private javax.swing.JButton btnReserve;
    private javax.swing.JButton btnReserveBooks;
    private javax.swing.JButton btnReturn;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSearch1;
    private javax.swing.JButton btnUpdateBooks1;
    private javax.swing.JButton btnViewBorrowed;
    private javax.swing.JComboBox<String> cmbxOpt;
    private javax.swing.JComboBox<String> cmbxOpt1;
    private javax.swing.JComboBox<String> cmbxViewSelect;
    private javax.swing.JTable finesTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanelBorrowBooks;
    private javax.swing.JPanel jPanelBorrowedBooks;
    private javax.swing.JPanel jPanelParent;
    private javax.swing.JPanel jPanelReserveBook;
    private javax.swing.JPanel jPanelReturnBook;
    private javax.swing.JPanel jPanelSideBar;
    private javax.swing.JPanel jPaneloverdue;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lbl;
    private javax.swing.JLabel lblLoging;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JLabel lblSearch1;
    private javax.swing.JLabel lblSpRemarks1;
    private javax.swing.JLabel lblauth;
    private javax.swing.JLabel lblauth1;
    private javax.swing.JLabel lblbk;
    private javax.swing.JLabel lblbk1;
    private javax.swing.JLabel lblgenre;
    private javax.swing.JLabel lblgenre1;
    private javax.swing.JLabel lblref;
    private javax.swing.JLabel lblref1;
    private javax.swing.JComboBox<String> selectBook;
    private javax.swing.JTextField txtAuthor;
    private javax.swing.JTextField txtAuthor1;
    private javax.swing.JTextField txtBookName;
    private javax.swing.JTextField txtBookName1;
    private javax.swing.JTextField txtGenre;
    private javax.swing.JTextField txtGenre1;
    private javax.swing.JTextField txtLoginAs;
    private javax.swing.JTextField txtRefId;
    private javax.swing.JTextField txtRefId2;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtSearch1;
    private javax.swing.JTextField txtSpRemarks1;
    // End of variables declaration//GEN-END:variables

}
